apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeshop-ingress
  namespace: kubeshop-lkc
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: kubeshop.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: kubeshop-api-svc
                port:
                  number: 80
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: kubeshop-web-svc
                port:
                  number: 80
